export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Welcome } from "./Welcome";
export { default as Account } from "./Account";
export { default as Courses } from "./Courses";
export { default as NewCourses } from "./NewCourses";
export { default as TopCourses } from "./TopCourses";
export { default as MyCourses } from "./MyCourses";
export { default as CourseDetails } from "./CourseDetails";